@startuml

title __PROPFACTORY's Class Diagram__\n

  namespace com.example.aircraftwar {
    namespace JavaCode.edu.hitsz {
      namespace prop.propfactory {
        class com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.BombFactory {
            + createProp()
        }
      }
    }
  }
  

  namespace com.example.aircraftwar {
    namespace JavaCode.edu.hitsz {
      namespace prop.propfactory {
        class com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.FireFactory {
            + createProp()
        }
      }
    }
  }
  

  namespace com.example.aircraftwar {
    namespace JavaCode.edu.hitsz {
      namespace prop.propfactory {
        class com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.HpFactory {
            + createProp()
        }
      }
    }
  }
  

  namespace com.example.aircraftwar {
    namespace JavaCode.edu.hitsz {
      namespace prop.propfactory {
        interface com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.PropFactory {
            {abstract} + createProp()
        }
      }
    }
  }
  

  com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.BombFactory .up.|> com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.PropFactory
  com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.FireFactory .up.|> com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.PropFactory
  com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.HpFactory .up.|> com.example.aircraftwar.JavaCode.edu.hitsz.prop.propfactory.PropFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
