@startuml

title __AIRCRAFTWAR's Class Diagram__\n

  namespace com.example.aircraftwar.JavaCode.edu.hitsz.application {
    class com.example.aircraftwar.JavaCode.edu.hitsz.application.HeroController {
        - game : Game
        - heroAircraft : HeroAircraft
        - mouseAdapter : MouseAdapter
        + HeroController()
    }
  }
  

  namespace com.example.aircraftwar.JavaCode.edu.hitsz.application {
    class com.example.aircraftwar.JavaCode.edu.hitsz.application.Main {
        {static} + BG : Bitmap
        {static} + FinalScore : int
        {static} + MAIN_LOCK : Object
        {static} + Username : String
        {static} + WINDOW_HEIGHT : int
        {static} + WINDOW_WIDTH : int
        {static} + gameParameter : int
        {static} + ifRecord : boolean
        {static} + soundSwitch : boolean
        {static} + main()
    }
  }
  

  namespace com.example.aircraftwar.JavaCode.edu.hitsz.application {
    class com.example.aircraftwar.JavaCode.edu.hitsz.application.MusicManager {
        {static} - bgm : MusicThread
        {static} - boss : MusicThread
        {static} - enable : boolean
        {static} - music : String[]
        {static} + Boss()
        {static} + BossDied()
        {static} + Enable()
        {static} + bgmBegin()
        {static} + bombBlow()
        {static} + bulletHit()
        {static} + gameOver()
        {static} + propGet()
    }
  }
  

  namespace com.example.aircraftwar.JavaCode.edu.hitsz.application {
    class com.example.aircraftwar.JavaCode.edu.hitsz.application.MusicThread {
        - audioFormat : AudioFormat
        - filename : String
        - isPlay : boolean
        - repeat : boolean
        - samples : byte[]
        + MusicThread()
        + getSamples()
        + letEnd()
        + play()
        + reverseMusic()
        + run()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
