@startuml

title __RECORDDAO's Class Diagram__\n

  namespace com.example.aircraftwar {
    namespace JavaCode.edu.hitsz {
      namespace RecordDao {
        class com.example.aircraftwar.JavaCode.edu.hitsz.RecordDao.Record {
            - recordId : int
            - recordRank : int
            - score : int
            - time : String
            - userName : String
            + Record()
            + getRecordId()
            + getRecordRank()
            + getScore()
            + getTime()
            + getUserName()
            + printRecord()
            + setRecordId()
            + setRecordRank()
            + setTime()
            + setUserName()
        }
      }
    }
  }
  

  namespace com.example.aircraftwar {
    namespace JavaCode.edu.hitsz {
      namespace RecordDao {
        interface com.example.aircraftwar.JavaCode.edu.hitsz.RecordDao.RecordDao {
            {abstract} + RecordsSort()
            {abstract} + doAdd()
            {abstract} + findByld()
            {abstract} + getAllRecords()
            {abstract} + printAllRecords()
        }
      }
    }
  }
  

  namespace com.example.aircraftwar {
    namespace JavaCode.edu.hitsz {
      namespace RecordDao {
        class com.example.aircraftwar.JavaCode.edu.hitsz.RecordDao.RecordDaoImpl {
            - records : List<Record>
            + RecordDaoImpl()
            + RecordsSort()
            + deleteAtMax()
            + deleteRecord()
            + doAdd()
            + findByld()
            + getAllRecords()
            + printAllRecords()
            + readRecords()
            + writeRecords()
        }
      }
    }
  }
  

  com.example.aircraftwar.JavaCode.edu.hitsz.RecordDao.Record .up.|> java.io.Serializable
  com.example.aircraftwar.JavaCode.edu.hitsz.RecordDao.RecordDaoImpl .up.|> com.example.aircraftwar.JavaCode.edu.hitsz.RecordDao.RecordDao


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
